### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by barbrady123** [GreyHak/dsp-csv-gen#25] opened 2022-06-21 04:08 UTC
Hey, just wondering if there's still support for this mod, or if it's been abandoned?  I notice it doesn't work with the current version of DSP and this is the MOST HELPFUL mod there is.  I have tried a couple different ways to extract the same data this provides and have had little luck.  Hope this mod makes a comeback, it's really great!  Thanks :)

**Comment by GreyHak** [comment] 2022-08-05 18:32
Anyone finding this ticket should feel free to comment here to show support for updating this issue. Right now it’s just not getting priority in my life.
Anyone wanting to fix the issue is free to create a pull request or fork.

**Comment by GreyHak** [comment] 2022-08-12 21:52
@barbrady123 Fix released in v4.0.0 thanks to @starfi5h

**Closed as completed by GreyHak** 2022-08-12 21:52 UTC
Labels: broken-by-update
