### ISSUE TITLE
DSP does not Generate the CSV file. Also Receiving Error when Clicking the Hud Button.

### ISSUE THREAD

**Issue by zkreeg** [GreyHak/dsp-csv-gen#26] opened 2022-08-05 17:40 UTC
DSP is not generating the csv file when I load a save or pause the game.

I also receive an error when I click the HUD button. Error is in the included attachment

![DSP Star Sector Resource Spreadsheet Generator](https://user-images.githubusercontent.com/29342528/183131571-ca596d5f-9d02-4e82-9be6-3309f268c05e.png)
.

**Comment by GreyHak** [comment] 2022-08-05 18:32
Thank you for the report @zkreeg
Anyone else finding this ticket should feel free to comment here to show support for updating this issue. Right now it’s just not getting priority in my life.
Anyone wanting to fix the issue is free to create a pull request or fork.

**Comment by ChinaShopBully** [comment] 2022-08-08 19:37
Love this mod! I think you're much mistaken in thinking this mod isn't deeply appreciated in the community. I see posts all the time lamenting the loss of this mod. Stick to a good work-life balance, GreyHak, but if you aren't working on it because you don't think we miss it, that's just not the case!

**Comment by GreyHak** [comment] 2022-08-12 21:52
@zkreeg @ChinaShopBully Fix released in v4.0.0 thanks to @starfi5h

**Closed as completed by GreyHak** 2022-08-12 21:52 UTC
Labels: broken-by-update

**Comment by ChinaShopBully** [comment] 2022-08-12 23:28
@GreyHak Fantastic! Thanks so much!

**Comment by zkreeg** [comment] 2022-08-13 02:10
Thank you for the update and merge!
